# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
# Enable C++ support
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - gcc-5
      env: COMPILER=g++-5.0
  include:
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
